[workspace]
members = [
  "crates/*",
  "apps/*",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/ChimiaDAO/chimiaclaw"
authors = ["ChimiaDAO"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
